#!/bin/sh
# DSB automounter
dsbmc-cli -a &
dsbmc &

# set locale
export LC_ALL=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
export LANG=C

# set input method
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

# execute uim/mozc as daemon
/usr/local/bin/mozc start
ibus-daemon -r --daemonize --xim

